#!/bin/bash
oPath=$(cd `dirname $0`; pwd)/
apk=$1

if [ -f $oPath$apk ]; then apk=$oPath$apk; fi

keyPath=${oPath}key
alias=alias1
storePass=000000
aliasPass=111111
buildTool=28.0.3

#进入buildTool目录
whereadb=$(whereis adb)
adbPath=${whereadb#* }
cd ${adbPath%/*}
cd ../build-tools/$buildTool

output=${apk}-temp.apk
./zipalign 4 $apk $output
mv $output $apk
./apksigner sign --v2-signing-enabled true --v1-signing-enabled true --ks $keyPath --ks-key-alias $alias --ks-pass pass:$storePass --key-pass pass:$aliasPass $apk